(self.AMP=self.AMP||[]).push({n:"amp-iframe",v:"2101230412005",m:0,f:(function(AMP,_){
'use strict';var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var q;a:{var ca={a:!0},r={};try{r.__proto__=ca;q=r.a;break a}catch(a){}q=!1}n=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n,u;function v(){return u?u:u=Promise.resolve(void 0)};function x(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var y=self.AMP_CONFIG||{},z=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ea(a){if(!self.document||!self.document.head||self.location&&z.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var fa={thirdParty:y.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:y.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof y.thirdPartyFrameRegex?new RegExp(y.thirdPartyFrameRegex):y.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:y.cdnUrl||ea("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:z,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:y.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:y.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:y.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:y.geoApiUrl||ea("amp-geo-api")};function ha(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];if(e instanceof Error&&!b){b=void 0;var f=Object.getOwnPropertyDescriptor(e,"message");if(f&&f.writable)b=e;else{f=e.stack;var g=Error(e.message);for(b in e)g[b]=e[b];g.stack=f;b=g}}else c&&(c+=" "),c+=e}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function ia(a){var b=ha.apply(null,arguments);setTimeout(function(){self.__AMP_REPORT_ERROR(b);throw b;})}self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};
var A=self.__AMP_LOG;function B(){if(!A.user)throw Error("failed to call initLogConstructor");return A.user}function C(){if(A.dev)return A.dev;throw Error("failed to call initLogConstructor");}function D(a,b,c,d,e){B().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function E(a){return a||{}};var F;function ja(a,b){var c=a,d=b;var e=function(g){try{return d(g)}catch(h){throw self.__AMP_REPORT_ERROR(h),h;}};var f=ka();c.addEventListener("message",e,f?void 0:!1);return function(){c&&c.removeEventListener("message",e,f?void 0:!1);e=c=d=null}}function ka(){if(void 0!==F)return F;F=!1;try{var a={get capture(){F=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return F};function la(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ma(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};function na(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function oa(a){return a.closest?a.closest(".i-amphtml-overlay"):na(a,function(b){var c=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return c?c.call(b,".i-amphtml-overlay"):!1})};function pa(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function qa(a){if(!ra(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(c){return C().error("MESSAGING","Failed to parse message: "+a,c),null}}function ra(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function sa(a,b){return ja(a,b)};function G(){this.ba=100;this.P=this.V=0;this.G=Object.create(null)}G.prototype.has=function(a){return!!this.G[a]};G.prototype.get=function(a){var b=this.G[a];if(b)return b.access=++this.P,b.payload};G.prototype.put=function(a,b){this.has(a)||this.V++;this.G[a]={payload:b,access:this.P};if(!(this.V<=this.ba)){C().warn("lru-cache","Trimming LRU cache");a=this.G;var c=this.P+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.V--)}};E({c:!0,v:!0,a:!0,ad:!0});var H,ta;
function ua(a){H||(H=self.document.createElement("a"),ta=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new G));var b=ta,c=H;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a};function va(a,b){for(var c=[],d=0,e=0;e<a.length;e++){var f=a[e];b(f,e,a)?c.push(f):(d<e&&(a[d]=f),d++)}d<a.length&&(a.length=d)}function wa(a,b){return 0>a.indexOf(b)?(a.push(b),!0):!1};var I,xa="Webkit webkit Moz moz ms O o".split(" ");function ya(a,b){var c=a.style;if("zIndex".startsWith("--"))c="zIndex";else{I||(I=Object.create(null));var d=I.zIndex;if(!d){d="zIndex";if(void 0===c.zIndex){var e;b:{for(e=0;e<xa.length;e++){var f=xa[e]+"ZIndex";if(void 0!==c[f]){e=f;break b}}e=""}void 0!==c[e]&&(d=e)}I.zIndex=d}c=d}c&&(c.startsWith("--")?a.style.setProperty(c,b):a.style[c]=b)};function za(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function Aa(a,b,c){var d=c?b.getAttribute("data-amp-3p-sentinel"):"amp";a=za(a,d,!0);for(d=0;d<a.length;d++){var e=a[d];if(e.frame===b){var f=e;break}}f||(f={frame:b,events:Object.create(null)},a.push(f));return f.events}
function Ba(a){for(var b=E({sentinel:"unlisten"}),c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,f;for(f in e)e[f].splice(0,Infinity).forEach(function(g){g(b)})}}}
function Ca(a){a.listeningFors||a.addEventListener("message",function(b){if(b.data){var c=Da(b.data);if(c&&c.sentinel){var d=b.source;var e=za(a,c.sentinel);if(e){for(var f,g=0;g<e.length;g++){var h=e[g],m=h.frame.contentWindow;if(m){var k;if(!(k=d==m))b:{for(k=d;k&&k!=k.parent;k=k.parent)if(k==m){k=!0;break b}k=!1}if(k){f=h;break}}else setTimeout(Ba,0,e)}d=f?f.events:null}else d=e;var w=d;if(w){var p=w[c.type];if(p)for(p=p.slice(),d=0;d<p.length;d++)(0,p[d])(c,b.source,b.origin,b)}}}})}
function J(a,b,c,d,e,f){function g(p,Q,R,Oa){if("amp"==p.sentinel){if(Q!=a.contentWindow)return;var Pa="null"==R&&f;if(m!=R&&!Pa)return}if(e||Q==a.contentWindow)"unlisten"==p.sentinel?w():c(p,Q,R,Oa)}var h=a.ownerDocument.defaultView;Ca(h);d=Aa(h,a,d);var m=ua(a.src).origin,k=d[b]||(d[b]=[]),w;k.push(g);return w=function(){if(g){var p=k.indexOf(g);-1<p&&k.splice(p,1);c=k=g=null}}}
function Ea(a,b,c,d,e){if(a.contentWindow)for(d.type=c,d.sentinel=e?a.getAttribute("data-amp-3p-sentinel"):"amp",a=d,e&&(a="amp-"+JSON.stringify(d)),d=0;d<b.length;d++)e=b[d],e.win.postMessage(a,e.origin)}function Da(a){"string"==typeof a&&(a="{"==a.charAt(0)?pa(a,function(b){C().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",b)})||null:ra(a)?qa(a):null);return a}
function K(a,b){var c=this;this.h=a;this.S=!1;this.D=[];this.da=J(this.h,"send-intersections",function(d,e,f){c.D.some(function(g){return g.win==e})||c.D.push({win:e,origin:f});b(d,e,f)},this.S,this.S)}K.prototype.send=function(a,b){va(this.D,function(c){return!c.win.parent});Ea(this.h,this.D,a,b,this.S)};K.prototype.destroy=function(){this.da();this.D.length=0};var L=[[300,250],[320,50],[300,50],[320,100]];function Fa(a,b,c){if(!(0==b&&0==c||0==a.width&&0==a.height)){b=a.left+b;c=a.top+c;var d=a.width;a=a.height;a={left:b,top:c,width:d,height:a,bottom:c+a,right:b+d,x:b,y:c}}return a};var Ga=[0,.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95,1];Date.now();function Ha(a,b){var c=this;this.aa=a;this.J=null;this.W=new K(b,function(){c.J.observe(c.aa.element)});this.J=new IntersectionObserver(function(d){c.W.send("intersection",E({changes:d.map(Ia)}))},{threshold:Ga})}Ha.prototype.destroy=function(){this.J.disconnect();this.J=null;this.W.destroy();this.W=null};
function Ia(a){return{time:a.time,rootBounds:a.rootBounds,boundingClientRect:a.boundingClientRect,intersectionRect:a.intersectionRect,intersectionRatio:a.intersectionRatio}};function M(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return N(a,b)}function O(a,b){a=P(a);a=S(a);return Ja(a,b)?N(a,b):null}function P(a){return a.nodeType?M((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function S(a){a=P(a);return a.isSingleDoc()?a.win:a}function N(a,b){Ja(a,b);a=T(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function Ka(a){var b=T(a).consentPolicyManager;if(b){if(b.promise)return b.promise;N(a,"consentPolicyManager");return b.promise=Promise.resolve(b.obj)}return null}function T(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}function Ja(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function La(){var a=new la,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};function Ma(a){if(a.__AMP__EXPERIMENT_TOGGLES)var b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(c=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){d=
d.getAttribute("content").split(",");for(var e=0;e<d.length;e++)-1!=c.indexOf(d[e])&&(b[d[e]]=!0)}c=Object;d=c.assign;e="";try{"localStorage"in a&&(e=a.localStorage.getItem("amp-experiment-toggles"))}catch(h){C().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}e=e?e.split(/\s*,\s*/g):[];for(var f=Object.create(null),g=0;g<e.length;g++)0!=e[g].length&&("-"==e[g][0]?f[e[g].substr(1)]=!1:f[e[g]]=!0);d.call(c,b,f);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&
0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];d=a.location.originalHash||a.location.hash;a=Object.create(null);if(d)for(;f=da.exec(d);)e=x(f[1],f[1]),f=f[2]?x(f[2].replace(/\+/g," "),f[2]):"",a[e]=f;for(d=0;d<c.length;d++)e=a["e-"+c[d]],"1"==e&&(b[c[d]]=!0),"0"==e&&(b[c[d]]=!1)}}return!!b["iframe-messaging"]};function Na(a){var b=Ka(S(a));if(b)return b;var c=P(a);return c.waitForBodyOpen().then(function(){var d=c.win;var e=c.win.document.head;if(e){var f={};e=e.querySelectorAll("script[custom-element],script[custom-template]");for(var g=0;g<e.length;g++){var h=e[g];h=h.getAttribute("custom-element")||h.getAttribute("custom-template");f[h]=!0}f=Object.keys(f)}else f=[];return f.includes("amp-consent")?M(d,"extensions").waitForExtension(d,"amp-consent"):v()}).then(function(){var d=c.win;if(d.__AMP_EXTENDED_ELEMENTS&&
d.__AMP_EXTENDED_ELEMENTS["amp-consent"]){d=S(a);var e=Ka(d);e?d=e:(d=T(d),d.consentPolicyManager=La(),d=d.consentPolicyManager.promise)}else d=null;return d})};function Qa(a,b){return Na(a).then(function(c){var d=E({consentMetadata:c&&c.getConsentMetadataInfo,consentString:c&&c.getConsentStringInfo,consentPolicyState:c&&c.whenPolicyResolved,consentPolicySharedData:c&&c.getMergedSharedData});return c?Promise.all(Object.keys(d).map(function(e){return d[e].call(c,b||"default").then(function(f){var g={};return g[e]=f,g})})).then(function(e){return Object.assign.apply({},e)}):d})};var Ra={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0,"AMP-LIGHTBOX-GALLERY":!0};function Sa(a,b){Ta(a).observe(a,b)}function U(a){var b=this,c=a.win;this.j=[];var d=this.ca.bind(this);this.j.push(new c.IntersectionObserver(d,{root:a.getBody(),threshold:.51}));this.j.push(new c.IntersectionObserver(d,{threshold:.51}));this.l=a.isVisible();this.$=a.onVisibilityChanged(function(){a.isVisible()!==b.l&&(b.l=a.isVisible(),Ua(b))});this.A=new Map;this.o=new Map}U.prototype.dispose=function(){this.j.forEach(function(a){return a.disconnect()});this.$();this.$=null;this.A.clear();this.o.clear()};
U.prototype.observe=function(a,b){var c=this,d=this.A.get(a);if(!d){d=[];this.A.set(a,d);for(var e=0;e<this.j.length;e++)this.j[e].observe(a)}wa(d,b)&&this.o.has(a)&&setTimeout(function(){var f=V(c.o.get(a),c.l);if(null!=f)try{b(f)}catch(g){ia(g)}})};U.prototype.unobserve=function(a,b){var c=this.A.get(a);if(c&&(b=c.indexOf(b),-1!=b&&c.splice(b,1),0==c.length))for(this.A.delete(a),this.o.delete(a),c=0;c<this.j.length;c++)this.j[c].unobserve(a)};
function Ua(a){a.A.forEach(function(b,c){var d=a.o.get(c),e=V(d,!a.l),f=V(d,a.l);Va(b,f,e)})}U.prototype.ca=function(a,b){for(var c=new Set,d=a.length-1;0<=d;d--){var e=a[d],f=e.target,g=e.isIntersecting;if(!c.has(f)&&(c.add(f),e=this.A.get(f))){var h=this.o.get(f);if(!h){h=this.j.length;for(var m=Array(h),k=0;k<h;k++)m[k]=null;h=m;this.o.set(f,h)}f=V(h,this.l);m=this.j.indexOf(b);h[m]=g;h=V(h,this.l);Va(e,h,f)}}};
function Ta(a){var b=U,c=P(a),d=S(c),e=T(d),f=e.DisplayObserver;f||(f=e.DisplayObserver={obj:null,promise:null,resolve:null,reject:null,context:null,ctor:null,adopted:!1});f.ctor||f.obj||(f.ctor=b,f.context=c,f.adopted=!1,f.resolve&&N(d,"DisplayObserver"));a=P(a);a=S(a);return N(a,"DisplayObserver")}function V(a,b){return b?a?a.reduce(Wa):null:!1}function Wa(a,b){return a||b?!0:!1===a&&!1===b?!1:null}function Va(a,b,c){if(null!=b&&b!==c)for(c=0;c<a.length;c++)try{(0,a[c])(b)}catch(d){ia(d)}};var Xa="allowfullscreen allowpaymentrequest allowtransparency allow frameborder referrerpolicy scrolling tabindex title".split(" "),Ya=0;function W(a){a=AMP.BaseElement.call(this,a)||this;a.N=null;a.K=!1;a.T=!1;a.F=!1;a.Z=!1;a.R=null;a.h=null;a.U=!1;a.L=!1;a.I=null;a.C="";a.O=null;a.iframeSrc=null;a.H=null;a.B=null;a.Y=!1;a.M=a.M.bind(a);return a}var X=AMP.BaseElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;
if(t)t(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Za=Object.getOwnPropertyDescriptor(X,Y);Za&&Object.defineProperty(W,Y,Za)}else W[Y]=X[Y];W.fa=X.prototype;l=W.prototype;l.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
function $a(a,b,c){var d=window.location.href,e=c=void 0===c?"":c;a=a.element;var f=O(a,"url"),g=f.parse(b),h=g.hostname,m=g.protocol;g=g.origin;D(f.isSecure(b)||"data:"==m,"Invalid <amp-iframe> src. Must start with https://. Found %s",a);var k=f.parse(d);D(!/\sallow-same-origin\s/i.test(" "+e+" ")||g!=k.origin&&"data:"!=m,"Origin of <amp-iframe> must not be equal to container %s if allow-same-origin is set. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",
a);D(!(ma(h,"."+fa.thirdPartyFrameHost)||ma(h,".ampproject.org")),"amp-iframe does not allow embedding of frames from ampproject.*: %s",b);return b}
function ab(a){var b=a.element.getLayoutBox(),c=Math.min(600,.75*a.getViewport().getSize().height);D(b.top>=c,"<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): %s  Current position %s. Min: %sPositioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.",a.element,b.top,c)}
function bb(a,b){if(b){a=O(a.element,"url").parse(b);var c=a.hash;"data:"==a.protocol||c&&"#"!=c||(a=b.indexOf("#"),b=(-1==a?b:b.substring(0,a))+"#amp=1");return b}}l.preconnectCallback=function(a){this.iframeSrc&&M(this.win,"preconnect").url(this.getAmpDoc(),this.iframeSrc,a)};
l.buildCallback=function(){this.C=this.element.getAttribute("sandbox");var a;if(!(a=bb(this,this.element.getAttribute("src"))))if(a=this.element.getAttribute("srcdoc")){D(!(" "+this.C+" ").match(/\s+allow-same-origin\s+/i),"allow-same-origin is not allowed with the srcdoc attribute %s.",this.element);if("undefined"!==typeof TextEncoder)var b=(new TextEncoder("utf-8")).encode(a);else{a=unescape(encodeURIComponent(a));b=new Uint8Array(a.length);for(var c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=
d}}a=btoa;c=Array(b.length);for(d=0;d<b.length;d++)c[d]=String.fromCharCode(b[d]);b=c.join("");a="data:text/html;charset=utf-8;base64,"+a(b)}else a=void 0;this.iframeSrc=$a(this,a,this.C);this.N=this.getPlaceholder();this.K=!!this.N;(this.L=this.element.hasAttribute("resizable"))&&this.element.setAttribute("scrolling","no");this.element.hasAttribute("frameborder")||this.element.setAttribute("frameborder","0");a=this.element;"no"!=a.getAttribute("scrolling")&&(b=a.ownerDocument.createElement("i-amphtml-scroll-container"),
a.appendChild(b),a=b);this.H=a;cb(this)};
l.onLayoutMeasure=function(){db(this);var a=this.element;a:{var b=a.getLayoutSize();var c=b.width;b=b.height;for(var d=0;d<L.length;d++){var e=L[d][0],f=L[d][1];if(!(f>b||e>c)&&20>=b-f&&20>=c-e){c=!0;break a}}c=!1}this.T=c;c=this.element;b=c.getLayoutSize();d=b.height;this.F=10<b.width||10<d?!1:!oa(c);if(c=this.T){c=this.win;b=!1;d=0;do Ra[a.tagName]?(d++,b=!1):(e=(c.getComputedStyle(a)||Object.create(null)).position,"fixed"!=e&&"sticky"!=e||(b=!0)),a=a.parentElement;while(a&&"BODY"!=a.tagName);c=
!(!b&&1>=d)}this.Z=c};function db(a){if(a.h){var b=a.getViewport().getLayoutRect(a.h),c=a.getLayoutBox();a.R=Fa(b,-c.left,-c.top)}}l.getIntersectionElementLayoutBox=function(){if(!this.h)return AMP.BaseElement.prototype.getIntersectionElementLayoutBox.call(this);var a=this.getLayoutBox();this.R||db(this);return Fa(this.R,a.left,a.top)};
l.layoutCallback=function(){var a=this;D(!this.Z,"amp-iframe is not used for displaying fixed ad. Please use amp-sticky-ad and amp-ad instead.");this.K||ab(this);this.L&&D(this.getOverflowElement(),"Overflow element must be defined for resizable frames: %s",this.element);if(!this.iframeSrc)return v();if(this.F&&!this.getAmpDoc().registerSingleton(1))return console.error("Only 1 analytics/tracking iframe allowed per page. Please use amp-analytics instead or file a GitHub issue for your use case: https://github.com/ampproject/amphtml/issues/new"),
v();var b=this.element.ownerDocument.createElement("iframe");this.h=b;this.applyFillContent(b);b.name="amp_iframe"+Ya++;this.K&&ya(b,-1);this.propagateAttributes(Xa,b);var c=b.getAttribute("allow")||"";c=c.replace("autoplay","autoplay-disabled");b.setAttribute("allow",c);b.setAttribute("sandbox",this.C||"");b.src=this.iframeSrc;this.F||(this.I=new Ha(this,b));b.onload=function(){b.readyState="complete";a.X();a.F&&(a.iframeSrc=null,N(a.win,"timer").promise(5E3).then(function(){b.parentElement&&b.parentElement.removeChild(b);
a.element.setAttribute("amp-removed","");a.h=null}))};J(b,"embed-size",function(d){Z(a,d.height,d.width)},void 0,void 0,!0);this.O=sa(this.win,function(d){if(a.h&&d.source===a.h.contentWindow&&(d=d.data,"string"===typeof d&&d.startsWith("pym"))){var e=d.split(/xPYMx/);"height"===e[2]?Z(a,parseInt(e[3],10),void 0):"width"===e[2]?Z(a,void 0,parseInt(e[3],10)):B().warn("amp-iframe","Unsupported Pym.js message: "+d)}});this.K&&J(b,"embed-ready",this.X.bind(this));J(b,"send-consent-data",function(d,e,
f){eb(a,e,f)});this.H.appendChild(b);this.U=!1;Sa(this.element,this.M);return this.loadPromise(b).then(function(){a.H!=a.element&&N(a.win,"timer").delay(function(){a.mutateElement(function(){a.H.classList.add("amp-active")})},1E3)})};function eb(a,b,c){Qa(a.element,a.getConsentPolicy()).then(function(d){var e=Object.assign(E({sentinel:"amp",type:"consent-data"}),d);b.postMessage(e,c)})}
l.unlayoutCallback=function(){var a=this.element,b=this.M;Ta(a).unobserve(a,b);this.O&&(this.O(),this.O=null);this.h&&(a=this.h,a.parentElement&&a.parentElement.removeChild(a),this.N&&this.togglePlaceholder(!0),this.h=null,this.I&&(this.I.destroy(),this.I=null));return!0};l.getLayoutPriority=function(){return this.T?2:this.F?1:AMP.BaseElement.prototype.getLayoutPriority.call(this)};
l.mutatedAttributesCallback=function(a){var b=a.src;void 0!==b&&(this.iframeSrc=bb(this,b),this.h&&(this.h.src=$a(this,this.iframeSrc,this.C)));this.h&&a.title&&this.propagateAttributes(["title"],this.h)};l.unlayoutOnPause=function(){return!0};l.M=function(a){var b=this;if(a!==this.U){this.U=a;var c=!!this.element.getOwner();a||c||!this.h||this.getVsync().mutate(function(){return b.unload()})}};l.X=function(){var a=this;this.N&&this.getVsync().mutate(function(){a.h&&(ya(a.h,0),a.togglePlaceholder(!1))})};
l.firstLayoutCompleted=function(){};l.throwIfCannotNavigate=function(){if(!/\sallow-top-navigation\s/i.test(" "+this.C+" "))throw B().createError('"AMP.navigateTo" is only allowed on <amp-iframe> when its "sandbox" attribute contains "allow-top-navigation".');};
function Z(a,b,c){if(a.L)if(100>b)a.user().error("amp-iframe","Ignoring embed-size request because the resize height is less than 100px. If you are using amp-iframe to display ads, consider using amp-ad instead.",a.element);else{var d,e;b=parseInt(b,10);isNaN(b)||(d=Math.max(b+(a.element.offsetHeight-a.h.offsetHeight),b));c=parseInt(c,10);isNaN(c)||(e=Math.max(c+(a.element.offsetWidth-a.h.offsetWidth),c));void 0!==d||void 0!==e?a.attemptChangeSize(d,e).then(function(){void 0!==d&&a.element.setAttribute("height",
d);void 0!==e&&a.element.setAttribute("width",e);a.element.overflowCallback(!1,d,e)},function(){}):a.user().error("amp-iframe","Ignoring embed-size request because no width or height value is provided",a.element)}else a.Y||(a.user().error("amp-iframe","Ignoring embed-size request because this iframe is not resizable",a.element),a.Y=!0)}
function cb(a){if(Ma(a.win)){var b=a.element,c=b.getAttribute("src");c&&(a.B=O(b,"url").parse(c).origin);a.registerAction("postMessage",function(f){a.B?a.h.contentWindow.postMessage(f.args,a.B):B().error("amp-iframe",'"postMessage" action is only allowed with "src"attribute with an origin.')});if(a.B){var d=0,e=function(f){if(f.source===a.h.contentWindow)if(f.origin!==a.B)B().error("amp-iframe",'"message" received from unexpected origin: '+f.origin+". Only allowed from: "+a.B);else{if(a.getAmpDoc().getRootNode().activeElement!==
a.h)var g=!1;else g=a.win.document.createElement("audio"),g.play(),g=g.paused?!1:!0;if(g){var h=f.data;try{var m=JSON.parse(JSON.stringify(h))}catch(w){B().error("amp-iframe",'Data from "message" event must be JSON.');return}var k=a.win;f=E({data:m});g={detail:f};Object.assign(g,void 0);"function"==typeof k.CustomEvent?f=new k.CustomEvent("amp-iframe:message",g):(k=k.document.createEvent("CustomEvent"),k.initCustomEvent("amp-iframe:message",!!g.bubbles,!!g.cancelable,f),f=k);O(a.element,"action").trigger(a.element,
"message",f,3)}else d++,B().error("amp-iframe",'"message" event may only be triggered from a user gesture.'),10<=d&&(B().error("amp-iframe",'Too many non-gesture-triggered "message" events; detaching event listener.'),a.win.removeEventListener("message",e))}};a.win.addEventListener("message",e)}}}l.ea=function(a){this.B=a};(function(a){a.registerElement("amp-iframe",W)})(self.AMP);
})});

//# sourceMappingURL=amp-iframe-0.1.js.map
